// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.
import type { Asset, Entry } from 'contentful';

export interface IDatacvFields {
    /** Main title (name) */
    name: string;

    /** Occupation */
    occupation?: string | undefined;

    /** phone */
    phone?: Entry<{ [fieldId: string]: unknown }> | undefined;

    /** phoneShort */
    short?: string | undefined;

    /** phoneFull */
    full?: string | undefined;
}

/** data for useless-cv */

export interface IDatacv extends Entry<IDatacvFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: 'datacv';
                linkType: 'ContentType';
                type: 'Link';
            };
        };
    };
}

export type CONTENT_TYPE = 'datacv';

export type IEntry = IDatacv;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
