name: course-rating CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
              env:
                  MONGO_URI: ${{ secrets.MONGO_URI }}
                  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
                  AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
                  AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
                  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
                  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
                  MAIL_REFRESH_TOKEN: ${{ secrets.MAIL_REFRESH_TOKEN }}
                  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
                  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
                  RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
